### ISSUE TITLE
Feature request And Bug

### ISSUE THREAD

**Issue by xkcdjerry** [uuk0/mcpython-4#1] opened 2019-08-21 08:46 UTC
Bug:
sometimes the player will go to one side, I tried everything, and all I can do is slow it down, so,I slipped over the edge...
Feature Request:
1:make player die or tp back to the ground level, or he will keep falling forever
2:make bedrock in-destructable
3:make blocks appear in the inventory or hotbar when they are mined

**Comment by uuk0** [comment] 2019-08-21 19:11
Thank you for the first bug / feature request!

The bug comes from an old code system which was extended not correct. I will change it in furture. It is not correct reseted wheyou leave normal game (for exaple to the escape menu) and releasethe key.

Response to your feature response:
1. I thought I had implemented these in the past. Will come soon, thanks for suggesting
2. Because I have implemented an chat-system with commands and gamemode-system and default gamemode is 1 (which will be selectable in future), change it by simple pressing t and entering "/gamemode 0"
3. same as 2., in gamemode 1, blocks are not given back

**Comment by uuk0** [comment] 2019-08-21 19:31
should be fixed and implemented in latets commit

**Comment by xkcdjerry** [comment] 2019-08-28 08:26
First, I thank you for implementing my feature requests!
But during my play, I still found some small hiccups, they are as follows:
Unfixed Bug:
    Still will move wrong when I press the escape key and release the key
Feature Request:
    make player go into gamemode 0 by default
    make player able to fly when in gamemode 1
Bug:
    1:player will be stuck in the rocks when the game starts
![image](https://user-images.githubusercontent.com/49294431/63837659-7a9b4780-c9ae-11e9-8a65-f70d94b6fda2.png)
![image](https://user-images.githubusercontent.com/49294431/63837675-84bd4600-c9ae-11e9-86c5-8d987e7161d6.png)
![image](https://user-images.githubusercontent.com/49294431/63837691-8d158100-c9ae-11e9-962c-5d2b39cc2c17.png)
![image](https://user-images.githubusercontent.com/49294431/63837723-9b639d00-c9ae-11e9-9d39-17984e4a9d71.png)
![image](https://user-images.githubusercontent.com/49294431/63837736-a1f21480-c9ae-11e9-9f40-bed86cec5826.png)
![image](https://user-images.githubusercontent.com/49294431/63837781-af0f0380-c9ae-11e9-9c93-9a23d82faece.png)


    2:the player will be pure black when I press e
![image](https://user-images.githubusercontent.com/49294431/63837885-e67db000-c9ae-11e9-931b-b56871ea022f.png)

    3:if i dig down to bedrock, I will fall-rise-fall forever(sorry, I cant get a picture)
    4:the game gives this warning:
[warning] running behind normal tick, did you overload game? missing 5.584453189333332 seconds
    5:if I start a new game, the game will crash, Trackback is below:
![image](https://user-images.githubusercontent.com/49294431/63838329-ba166380-c9af-11e9-8693-022e73514b35.png)

**Comment by xkcdjerry** [comment] 2019-08-28 08:27
PS: Can you speed up the loading? It takes a painfully long time
PPS: Can you look at my game?It's at https://github.com/xkcdjerry/Tank-Wars
Thank you!

**Comment by uuk0** [comment] 2019-08-28 17:20
Thank you for the new feature requests and new bugs

1. Ok, I think I have to re-write the whole move system.
2. If I have time, the start menu will get an update with some configs
3. Press tab and fly (key will be changed in future)
4. I not fully implemented the height map system and these is left from old world generation. Will be fixed soon
5. I have no entities implemented so no player image :(
6. Warning comes from some code which looks at updates per second. Is printed out when long tasks (world generation, ...) take long time to finish.
6. Ok, the System which removes all blocks from world seems broken
7. Yes, I know. I am testing at the moment some code which makes it better, but I don't know when it will be finished
8. On weekend, I will have a look

I will try to fix most of the above bugs on weekend

**Comment by xkcdjerry** [comment] 2019-08-29 00:43
Old Issue:if i dig down to bedrock, I will fall-rise-fall forever(sorry, I cant get a picture)
Correction: If I dig straight down from my spawn point and go through bedrock, then I will rise-fall-rise forever

PS: Can I help?

**Comment by uuk0** [comment] 2019-08-29 12:47
Ok, this an problem with spawn-system which definite xz coordinates.

**Comment by xkcdjerry** [comment] 2019-08-29 13:28
OK, I will write a function getcoords that returns (x, y, x) tuple

**Comment by xkcdjerry** [comment] 2019-08-29 13:29
May I ask where is the code that spawns the player?Thank you!

**Comment by xkcdjerry** [comment] 2019-08-29 13:37
What The Heck Is This???
![image](https://user-images.githubusercontent.com/49294431/63945001-3a6ac080-caa5-11e9-9c85-640002a333ed.png)

**Comment by uuk0** [comment] 2019-08-29 14:10
Code locations: 
-state/StateStartMenu.py in on_new_game_press: Last line of function
-world/player.py in kill
How to get right position:
Call G.world.get_active_dimension().get_chunk_for_position(G.window.position).get_value('highmap')[util.math.normalize(G.window.position)][0][1] which returns Max y position at xz of player

There is an configuration for Max view distance which let not everything render

**Comment by uuk0** [comment] 2019-08-29 15:39
G.window.position could be replaced by any position vector

**Comment by xkcdjerry** [comment] 2019-08-30 04:19
OK，working on it.

**Comment by xkcdjerry** [comment] 2019-08-30 04:22
> G.window.position could be replaced by any position vector

so,G.window.position is the position of the player, and that big blob gets the max y coords?

**Comment by xkcdjerry** [comment] 2019-08-30 04:35
Correction: it is no problem with the blocksize, there is a bug that keeps bloacks from being showed before the blocks beside them are mined

**Comment by xkcdjerry** [comment] 2019-08-30 04:40
PS: Where is the system that loads the blocks? I will speed it up.

**Comment by uuk0** [comment] 2019-08-30 07:39
Blocks are shown one by one during playing to minimize generation time

The problem is not block loading, it is the runtime-based Item Generation for Blocks located in state/StateBlockItemGenerator

I have missed in above code part for getting max y that the until.math.normalize returns xyz-tuple and xz is needed. So please remember this during implementing it

**Comment by xkcdjerry** [comment] 2019-08-30 07:43
> Blocks are shown one by one during playing to minimize generation time
> 
> The problem is not block loading, it is the runtime-based Item Generation for Blocks located in state/StateBlockItemGenerator
> 
> I have missed in above code part for getting max y that the until.math.normalize returns xyz-tuple and xz is needed. So please remember this during implementing it

what do you mean by the last point???

**Comment by xkcdjerry** [comment] 2019-08-30 07:43
oh

**Comment by xkcdjerry** [comment] 2019-08-30 07:44
got it

**Comment by xkcdjerry** [comment] 2019-08-30 07:59
I fixed the spawn system (sort of)
but why did you write a add_xp_level function
and why don't it use it's argument xp_levels
![image](https://user-images.githubusercontent.com/49294431/64003535-080da180-cb3f-11e9-858e-454cf184bebe.png)

**Comment by uuk0** [comment] 2019-08-30 08:11
Not used and not fully implemented.
I have forgotten to remove it

**Comment by xkcdjerry** [comment] 2019-08-30 08:12
So, I can remove it?

**Comment by xkcdjerry** [comment] 2019-08-30 08:13
So, I can remove it.

**Comment by xkcdjerry** [comment] 2019-08-30 08:15
OK

**Comment by xkcdjerry** [comment] 2019-08-30 08:17
By the way, I fixed you remove-world system

**Comment by uuk0** [comment] 2019-08-30 08:18
Good

Thank you for helping me

**Comment by xkcdjerry** [comment] 2019-08-30 08:19
I found a small bug, When The Player dies and he/she is moving, then he/she will jam into the ground(I forked yours, you can see the bug there

**Comment by xkcdjerry** [comment] 2019-08-30 08:27
![image](https://user-images.githubusercontent.com/49294431/64005367-d991c580-cb42-11e9-804a-d10b2b252dd6.png)

**Comment by xkcdjerry** [comment] 2019-08-30 08:30
Unfixed Bug:
Still will move wrong when I press the escape key and release the key
the player will be pure black when I press e
if i dig down to bedrock, I will fall-rise-fall forever
Feature Request:
make player go into gamemode 0 by default
make player able to fly when in gamemode 1
New Bug:
    if I try to dig a block in gamemode 0, the game crashes with this error message:
![image](https://user-images.githubusercontent.com/49294431/64005690-72c0dc00-cb43-11e9-82ed-92bae57972c3.png)

**Comment by xkcdjerry** [comment] 2019-08-30 08:33
Unfixed Bug:
the player will be pure black when I press e
if i dig down to bedrock, I will fall-rise-fall forever
Feature Request:
make player go into gamemode 0 by default
make player able to fly when in gamemode 1
make it possible to change slots by using the scroll on the mouse
New Bug:
if I try to dig a block in gamemode 0, the game crashes with this error message:
![](https://user-images.githubusercontent.com/49294431/64005690-72c0dc00-cb43-11e9-82ed-92bae57972c3.png)

**Comment by xkcdjerry** [comment] 2019-08-30 08:39
Unfixed Bug:
the player will be pure black when I press e
if i dig down to bedrock, I will fall-rise-fall forever(Correction: this is the same as MC)(You may choose not to fix this)
Feature Request:
make player go into gamemode 0 by default or give a menu(like MC)
make player able to fly using double spaces (like MC)
make it possible to change slots by using the scroll on the mouse(like MC)
New Bug:
if I try to dig a block in gamemode 0, the game crashes with this error message:
![](https://user-images.githubusercontent.com/49294431/64005690-72c0dc00-cb43-11e9-82ed-92bae57972c3.png)

**Comment by uuk0** [comment] 2019-08-30 08:54
Exists the bug before?

**Comment by xkcdjerry** [comment] 2019-08-30 08:55
What do you mean?

**Comment by uuk0** [comment] 2019-08-30 08:57
Did the same error occurred before your Ch anges

**Comment by xkcdjerry** [comment] 2019-08-30 08:59
If the player moved before, It will move after respawning too,but due to spawning in rocks, It is not that signifant

**Comment by uuk0** [comment] 2019-08-30 09:02
sorry, I thought about the exception in the image you posted

**Comment by xkcdjerry** [comment] 2019-08-30 09:03
Yes, It did happen.

**Comment by uuk0** [comment] 2019-08-30 09:07
Ok, then it was left over from braking world handling changes I made in the past.
Fix: use G.world.get_active_dimension().get_block(position).get_name()

**Comment by xkcdjerry** [comment] 2019-08-30 09:07
???

**Comment by xkcdjerry** [comment] 2019-08-30 09:08
Where do I put It?

**Comment by uuk0** [comment] 2019-08-30 09:12
Replace G.world.world[blockpos].get_name() with the code part in the last line of the exception

**Comment by xkcdjerry** [comment] 2019-08-30 09:12
OK

**Comment by xkcdjerry** [comment] 2019-08-30 09:15
I tried, but It crashed,maybe you can merge my request and change it at your end?

**Comment by xkcdjerry** [comment] 2019-08-30 09:18
Maybe I changed it wrong?

**Comment by uuk0** [comment] 2019-08-30 11:13
Can you give me the last line of the new exception?

**Comment by xkcdjerry** [comment] 2019-08-30 12:31
NameError: name 'position' is not defined

**Comment by xkcdjerry** [comment] 2019-08-30 12:45
Fixed it

**Comment by xkcdjerry** [comment] 2019-08-30 12:46
Some weird little bug: I can't put down blocks when in gamemode 0
but I can do so in gamemode 1
how do I fix it?

**Comment by uuk0** [comment] 2019-08-30 12:57
Maybe only a little more time pressing the key?

**Comment by uuk0** [comment] 2019-08-30 16:06
Oh, found bug and fixed it. I have checked for gamemode 2 instead of gamemode 0 in the system which adds blocks

**Comment by xkcdjerry** [comment] 2019-08-31 10:32
Feature request:make blocks hover like in MC and can be picked up, not just tp to the players inventory

**Comment by uuk0** [comment] 2019-08-31 12:18
Item rendering in the world as entities is a little bit complicated due to rotation, resizing, motion etc.
so it will take some time to implement

Normal entities should be implemented first to add some base code and experience in writing this kind of code

**Comment by xkcdjerry** [comment] 2019-09-02 04:36
OK,Maybe you can implement trees and crafting first, or the game will be boring.(What can you do if you cannot craft anything and can only walk around?)
PS:Can you please make the world infinite or/and add a save option? The first will fix the  rendering bug,the second will speed up the world loading,and all three will make the game much better
I am using a cellphone, so I can't type much, I will give you a full update later, thank you.

**Comment by uuk0** [comment] 2019-09-02 06:12
both is not that complicated. I will try to implement this next.
The world is infinite but is not generated. You can use after next commit /generate -10 -10 10 10 to generate an bigger area
Saving the world will not speed up due to the time consuming fact in world generation is adding blocks and showing them.
But for building saving is an good idea, so I will have an look at it also

**Comment by xkcdjerry** [comment] 2019-09-04 11:38
I think I have a better option: use dynamic loading:first,just generate one block,then, if the player is in, say 10blocks to the edge, the you can generate a new block,the player can still use a command, but an auto loading will speed up the initial load and give better game feels.
(it will feel terrible if I have to type a ton of commands just to go exploring)
Thank You!

**Comment by uuk0** [comment] 2019-09-05 14:21
I would not split by individual xz-positions.
World generation is splitted into seperated generation layers which perform diffrent tasks (create biome map, create height map, generate bedrock, generate stone, generate grass & dirt). These layers are generated per chunk.
An layer has an function which adds parts of the task to an chunk-internal map of tasks to perform.
These map can be executed all at ones or during playing the game step by step.
How much of the tasks are executed comes from the time they consume.

Simple implementation: process only all tasks in one chunk, the others afterwards

**Comment by xkcdjerry** [comment] 2019-09-09 11:51
For gods sake,can,you speed up the loading?It takes half a hour on my laptop…

**Comment by uuk0** [comment] 2019-09-09 11:56
Sorry for the problems with the program.

I'm currently working on an small internal change to registries, and than I will speed it up (I have an plan for speeding up so a lot of things are only done if in the program something related to the part which is re-build is changed).
It may be finished today, if not it could take some days because I have now other things to do which will shorten my free-time for working on it.

**Comment by xkcdjerry** [comment] 2019-09-13 07:25
Wow, the init loading and the 61 blocks are now much faster,thank you!May you tell me how did you manged it?Thanks a ton!
PS: Whats this?
![image](https://user-images.githubusercontent.com/49294431/64844359-20e77e00-d63a-11e9-89e9-ec891dbe9ae2.png)
PPS: This issue is WAY too long.It's a pain scrolling down it to the bottom,and much of it is already fixed. I will create a new one issue(with your agreement), no more bug/enhancement will be put on this issue, after all the bugs are fixed and all the enhancements done, may you do the honers of closing this issue when all the bug are fixed and all the enhancements are done?Thank you again!

**Comment by xkcdjerry** [comment] 2019-09-13 07:29
Hmm the image is broken on my FireFox, there is another right here……
![image](https://user-images.githubusercontent.com/49294431/64844786-327d5580-d63b-11e9-96e4-2a7516d2e38e.png)


and a text version just in case it breaks yet again:
---------------------
- Game Loading Area -
---------------------
generating textures...
loading blocks...
searching for models...
finished!
generating models...
generating image atlases...
finished!
----------------------------------------------
- END OF LOADING. NOW STARTING UPDATE CYCLES -
----------------------------------------------
loading recipes
 -loading recipe 757
recipes with errors: 186

**Comment by xkcdjerry** [comment] 2019-09-13 07:30
The point is, why is there a lot of error recipes(about 25%)? Thanks!

**Comment by xkcdjerry** [comment] 2019-09-13 07:45
Request: 
1.when player touches the ground, stop flying(or there will be that really weird thing when you touch down using Shift and some time later, you want to jump, you just spring up and hang the air......)
2.when you press "/" you enter into the command page automaticly(as if you had entered t+/)(as in MC)
Bug:
 I still can't craft:
![image](https://user-images.githubusercontent.com/49294431/64845473-dc111680-d63c-11e9-8e04-029b1b97f37c.png)
and the output of /help (aka /?) is super weird:
![image](https://user-images.githubusercontent.com/49294431/64845579-24c8cf80-d63d-11e9-9f0b-baaf06eb47ce.png)
here's a text version:
---------------
- HELP PAGE 1 -
---------------

---------------
- HELP PAGE 2 -
---------------
t
t
t
t
r
g
s
f
h
h
---------------
- HELP PAGE 3 -
---------------
h
h

**Comment by uuk0** [comment] 2019-09-13 11:48
first, the optimizing stuff is not finished yet and is not puplished here.
I don't know what you have changed with your setup and/or the python code, but it is good to here that is now working better. I will finish the optimisation anyway, may be usefull in future for loading times (there may come more to do on load)

Recipes with errors are all kind of errors, also these recipes that uses non-provided crafting systems like furnes. The recipes marked with error should be furnes-recipes, no recipe format errors because they are loaded direct out of the minecraft 1.14.4 executeable.
crafting is broken, I know, there where things that should be fixed before and the performens issue came in, so will be fixed in near future.

The help command is broken long time and I had forgotten to fix it. Will be fixed soon.

**Comment by xkcdjerry** [comment] 2019-09-13 11:51
hmm，may I correct you:
first, the optimizing  is not finished yet and is not published here.
I don't know what you have changed with your setup and/or the python code, but it is good to hear that is now working better. I will finish the optimization anyway, may be useful in future for loading times (there may come more to load)

Recipes with errors have all kind of errors, also these recipes that uses non-provided crafting systems like furnes. The recipes marked with error should be furnes-recipes, no recipe format errors because they are loaded direct out of the minecraft 1.14.4 executeable.
crafting is broken, I know, there are things that should be fixed before and the to-slow issue came in, so it will be fixed in near future.

The help command is broken for a long time and I had forgotten to fix it. Will be fixed soon.

**Comment by xkcdjerry** [comment] 2019-09-13 11:53
Am I right?
PS: what is a furn-recipe?

**Comment by uuk0** [comment] 2019-09-13 11:53
furnes recipes are things that can be smelted

**Comment by xkcdjerry** [comment] 2019-09-13 12:00
oh

**Comment by uuk0** [comment] 2019-09-14 10:43
I've looked into the crafting system and I know now that I have to implement an oredict / tag system in order to let most of the recipes work.
It make take a while to implement this (first, I have to fix a lot of other bugs), so only some recipes may work until then

**Closed as completed** 2019-09-22 12:20 UTC
Labels: bug, enhancement
